version: "3.2"
services:

  nats:
    container_name: nats
    image: nats:latest
    command: -p 4222 --cluster_name "py-msgp-cluster" -m 8222 -js -V
    restart: unless-stopped
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    networks:
      py-msgp-network:
        aliases:
          - nats

  # Run initContainers to check the availability of the fundamental services
  # and may initialize streams and consumers using JetStream
  #
  # NOTE: Add the following docker-compose code fragment to containers
  # that needs NATS services and want to use streams and comsumers:
  # 
  #  depends_on:
  #    init-nats-jetstream:
  #      condition: service_completed_successfully
  #
  init-nats-jetstream:
    container_name: init-nats-jetstream
    image: natsio/nats-box:0.8.1
    command: -c 'sh /scripts/init-nats-jetstream.sh'
    volumes:
      - ./scripts/init-nats-jetstream.sh:/scripts/init-nats-jetstream.sh
    networks:
      py-msgp-network:
        aliases:
          - init-nats-jetstream
    depends_on:
      - nats

  # Jaeger
  # NOTE: This container is used only for the examples
  jaeger-all-in-one:
    container_name: jaeger
    command: ["--query.max-clock-skew-adjustment", "0"]
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # Web HTTP
      - "14268:14268" # The HTTP port for the collector service
      - "14250:14250" # The gRPC port for the collector service
      - "5778:5778"   # Agent config HTTP
      - "4317:4317"   # OTLP Receiver gRPC port
      - "4318:4318"   # OTLP Receiver HTTP port
    environment:
      COLLECTOR_OTLP_ENABLED: "true" # Enables/Disables OTLP Receiver
    networks:
      py-msgp-network:
        aliases:
          - jaeger-all-in-one

networks:
  py-msgp-network:
