name: Release

on:
  push:
    branches:
      - master

jobs:
  qa:
    uses: tombenke/py-msgp/.github/workflows/qa.yml@master

  build:
    needs: qa
    runs-on: ubuntu-latest
    steps:
      - id: setup
        uses: tombenke/py-msgp/.github/actions/setup@master

      - id: checkout
        uses: tombenke/py-msgp/.github/actions/checkout@master

      - name: Run Docker build task
        run: task build-docker

      - name: Push docker images
        run: task push-docker
