name: Release

on:
  push:
    branches:
      - master

jobs:
  qa:
    uses: tombenke/py-messenger/.github/workflows/qa.yml@v0.3.0

  build:
    needs: qa
    runs-on: ubuntu-latest
    steps:
      - id: setup
        uses: tombenke/py-messenger/.github/actions/setup@v0.3.0

      - id: checkout
        uses: tombenke/py-messenger/.github/actions/checkout@v0.3.0

      - name: Run Docker build task
        run: task build-docker

      - name: Push docker images
        run: task push-docker
